<?
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_5ea33f1d22bd0',
	'title' => 'Настройки темы',
	'fields' => array(
		array(
			'key' => 'field_6483130a3652e',
			'label' => 'Шапка',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'no_preference' => 0,
		),
		array(
			'key' => 'field_6481d0d7e7c69',
			'label' => 'Верхняя шапка',
			'name' => 'top_contacts',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Добавить',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6481d19ae0907',
					'label' => 'Иконка',
					'name' => 'ikonka',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'uploader' => '',
					'acfe_thumbnail' => 0,
					'parent_repeater' => 'field_6481d0d7e7c69',
				),
				array(
					'key' => 'field_6481d137e7c6a',
					'label' => 'Наименование',
					'name' => 'naimenovanie',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6481d0d7e7c69',
				),
				array(
					'key' => 'field_6481d176e0906',
					'label' => 'Оформить ссылкой',
					'name' => 'oformit_ssylkoj',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'ui' => 1,
					'style' => '',
					'parent_repeater' => 'field_6481d0d7e7c69',
				),
				array(
					'key' => 'field_6483073048e4a',
					'label' => 'Двойное значение',
					'name' => 'dvojnoe_znachenie',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'ui' => 1,
					'style' => '',
					'parent_repeater' => 'field_6481d0d7e7c69',
				),
				array(
					'key' => 'field_6481d145e7c6b',
					'label' => 'Значение',
					'name' => 'znachenie',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6481d0d7e7c69',
				),
				array(
					'key' => 'field_6483078648e4b',
					'label' => 'Значение 2',
					'name' => 'znachenie_2',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6483073048e4a',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6481d0d7e7c69',
				),
				array(
					'key' => 'field_6483079848e4c',
					'label' => 'Анкор сслыки',
					'name' => 'ankor_sslyki',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6483073048e4a',
								'operator' => '==',
								'value' => '1',
							),
							array(
								'field' => 'field_6481d176e0906',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6481d0d7e7c69',
				),
				array(
					'key' => 'field_648307a548e4d',
					'label' => 'Анкор сслыки 2',
					'name' => 'ankor_sslyki_2',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6483073048e4a',
								'operator' => '==',
								'value' => '1',
							),
							array(
								'field' => 'field_6481d176e0906',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6481d0d7e7c69',
				),
				array(
					'key' => 'field_64a2e4d1dec4f',
					'label' => 'Цвет значение',
					'name' => 'color1',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 0,
					'return_format' => 'string',
					'display' => 'default',
					'button_label' => 'Select Color',
					'color_picker' => true,
					'absolute' => false,
					'input' => true,
					'allow_null' => true,
					'theme_colors' => false,
					'colors' => array(
					),
					'parent_repeater' => 'field_6481d0d7e7c69',
				),
				array(
					'key' => 'field_64a2e50cdec50',
					'label' => 'Цвет значение 2',
					'name' => 'color2',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6483073048e4a',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 0,
					'return_format' => 'string',
					'display' => 'default',
					'button_label' => 'Select Color',
					'color_picker' => true,
					'absolute' => false,
					'input' => true,
					'allow_null' => true,
					'theme_colors' => false,
					'colors' => array(
					),
					'parent_repeater' => 'field_6481d0d7e7c69',
				),
			),
			'acfe_repeater_stylised_button' => 0,
		),
		array(
			'key' => 'field_65199217a4ce2',
			'label' => 'Основное наполнение шапки',
			'name' => 'main_header_data_content',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_field_group_condition' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_6519927ba4ce3',
					'label' => 'Отсуп данных сверху в PX',
					'name' => 'margin-top',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_6519929fa4ce5',
					'label' => 'Отсуп данных снизу в PX',
					'name' => 'margin-bottom',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63e685ecd6d1a',
					'label' => 'Логотип',
					'name' => 'logo',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'thumbnail',
					'uploader' => '',
					'acfe_thumbnail' => 0,
				),
				array(
					'key' => 'field_63e68584d4dbf',
					'label' => 'Описание рядом с логотипом',
					'name' => 'logo_description',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'rows' => 4,
					'placeholder' => '',
					'new_lines' => 'br',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_64a3f367ce958',
					'label' => 'Включить отображение смены языка',
					'name' => 'lang-swithcer',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'ui' => 1,
					'style' => '',
				),
				array(
					'key' => 'field_651aec32b4b72',
					'label' => 'Настройка кнопки в шапке',
					'name' => 'button_set',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'acfe_seamless_style' => 0,
					'acfe_group_modal' => 0,
					'acfe_field_group_condition' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_651ae3e5eba0f',
							'label' => 'Высота кнопки',
							'name' => 'button_height',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_field_group_condition' => 0,
							'default_value' => '',
							'min' => '',
							'max' => '',
							'placeholder' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_651ae403eba10',
							'label' => 'Ширина кнопки',
							'name' => 'button_width',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_field_group_condition' => 0,
							'default_value' => '',
							'min' => '',
							'max' => '',
							'placeholder' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_651ae43eeba13',
							'label' => 'Размер шрифта',
							'name' => 'button_font-size',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_field_group_condition' => 0,
							'default_value' => '',
							'min' => '',
							'max' => '',
							'placeholder' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_651af18e5139e',
							'label' => 'Толщина шрифта',
							'name' => 'font_weight',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_field_group_condition' => 0,
							'choices' => array(
								300 => 'Тонкий (300)',
								400 => 'Нормальный (400)',
								500 => 'Средний (500)',
								600 => 'Полужирный (600)',
								700 => 'Жирный (700)',
								800 => 'Полутяжелый (800)',
								900 => 'Тяжелый (900)',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'prepend' => '',
							'append' => '',
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'allow_custom' => 0,
							'search_placeholder' => '',
							'min' => '',
							'max' => '',
						),
						array(
							'key' => 'field_651ae484eba15',
							'label' => 'Закругление углов',
							'name' => 'button_border-radius',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_field_group_condition' => 0,
							'default_value' => '',
							'min' => '',
							'max' => '',
							'placeholder' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_651ae417eba11',
							'label' => 'Цвет кнопки',
							'name' => 'button_color',
							'aria-label' => '',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_field_group_condition' => 0,
							'default_value' => '',
							'enable_opacity' => 0,
							'return_format' => 'string',
							'display' => 'default',
							'button_label' => 'Select Color',
							'color_picker' => 1,
							'absolute' => 0,
							'input' => 1,
							'allow_null' => 1,
							'theme_colors' => 0,
							'colors' => array(
							),
						),
						array(
							'key' => 'field_651ae42ceba12',
							'label' => 'Цвет кнопки при наведение',
							'name' => 'button_color_hover',
							'aria-label' => '',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_field_group_condition' => 0,
							'default_value' => '',
							'enable_opacity' => 0,
							'return_format' => 'string',
							'display' => 'default',
							'button_label' => 'Select Color',
							'color_picker' => 1,
							'absolute' => 0,
							'input' => 1,
							'allow_null' => 1,
							'theme_colors' => 0,
							'colors' => array(
							),
						),
						array(
							'key' => 'field_651ae45beba14',
							'label' => 'Цвет шрифта',
							'name' => 'button_text-color',
							'aria-label' => '',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_field_group_condition' => 0,
							'default_value' => '',
							'enable_opacity' => 0,
							'return_format' => 'string',
							'display' => 'default',
							'button_label' => 'Select Color',
							'color_picker' => 1,
							'absolute' => 0,
							'input' => 1,
							'allow_null' => 1,
							'theme_colors' => 0,
							'colors' => array(
							),
						),
					),
					'acfe_group_modal_close' => 0,
					'acfe_group_modal_button' => '',
					'acfe_group_modal_size' => 'large',
				),
				array(
					'key' => 'field_64ccc421d1015',
					'label' => 'Основные данные в шапке',
					'name' => 'main_header_data',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 1,
					'layout' => 'block',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => 'field_64ccc461d1017',
					'button_label' => 'Добавить',
					'acfe_field_group_condition' => 0,
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_651ae1f8eba0c',
							'label' => 'Тип объекта',
							'name' => 'object_type',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_field_group_condition' => 0,
							'choices' => array(
								'contact_item' => 'Контактные данные',
								'modal_form_buttom' => 'Кнопка вызова формы обратной связи',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'max' => '',
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'allow_custom' => 0,
							'search_placeholder' => '',
							'min' => '',
							'parent_repeater' => 'field_64ccc421d1015',
						),
						array(
							'key' => 'field_651ae2f4eba0d',
							'label' => 'Контактные данные',
							'name' => 'cotact_item',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_651ae1f8eba0c',
										'operator' => '==',
										'value' => 'contact_item',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_field_group_condition' => 0,
							'layout' => 'block',
							'acfe_seamless_style' => 0,
							'acfe_group_modal' => 0,
							'sub_fields' => array(
								array(
									'key' => 'field_64ccc461d1017',
									'label' => 'Название',
									'name' => 'name',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'acfe_field_group_condition' => 0,
								),
								array(
									'key' => 'field_64ccc8f7c9ce3',
									'label' => 'Размер шрифта названия в PX',
									'name' => 'name_fontsize',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'min' => '',
									'max' => '',
									'placeholder' => '',
									'step' => '',
									'prepend' => '',
									'append' => '',
									'acfe_field_group_condition' => 0,
								),
								array(
									'key' => 'field_64ccc75bd101b',
									'label' => 'Цвет названия',
									'name' => 'name_color',
									'aria-label' => '',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'enable_opacity' => 0,
									'return_format' => 'string',
									'display' => 'default',
									'button_label' => 'Select Color',
									'color_picker' => 1,
									'absolute' => 0,
									'input' => 1,
									'allow_null' => 1,
									'theme_colors' => 0,
									'colors' => array(
									),
									'acfe_field_group_condition' => 0,
								),
								array(
									'key' => 'field_64ccca8c74eb0',
									'label' => 'Толщина шрифта названия',
									'name' => 'font_weight_name',
									'aria-label' => '',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										300 => 'Тонкий (300)',
										400 => 'Нормальный (400)',
										500 => 'Средний (500)',
										600 => 'Полужирный (600)',
										700 => 'Жирный (700)',
										800 => 'Полутяжелый (800)',
										900 => 'Тяжелый (900)',
									),
									'default_value' => false,
									'return_format' => 'value',
									'multiple' => 0,
									'max' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'allow_null' => 0,
									'ui' => 0,
									'acfe_field_group_condition' => 0,
									'ajax' => 0,
									'allow_custom' => 0,
									'search_placeholder' => '',
									'min' => '',
								),
								array(
									'key' => 'field_64ccc474d1018',
									'label' => 'Значение',
									'name' => 'value',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'acfe_field_group_condition' => 0,
								),
								array(
									'key' => 'field_64ccc89dc9ce2',
									'label' => 'Размер шрифта значения в PX',
									'name' => 'value_fontsize',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'min' => '',
									'max' => '',
									'placeholder' => '',
									'step' => '',
									'prepend' => '',
									'append' => '',
									'acfe_field_group_condition' => 0,
								),
								array(
									'key' => 'field_64ccc737d101a',
									'label' => 'Цвет значения',
									'name' => 'value_color',
									'aria-label' => '',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'enable_opacity' => 0,
									'return_format' => 'string',
									'display' => 'default',
									'button_label' => 'Select Color',
									'color_picker' => 1,
									'absolute' => 0,
									'input' => 1,
									'allow_null' => 1,
									'theme_colors' => 0,
									'colors' => array(
									),
									'acfe_field_group_condition' => 0,
								),
								array(
									'key' => 'field_64cccc6d6698d',
									'label' => 'Толщина шрифта значения',
									'name' => 'font_weight_value',
									'aria-label' => '',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										300 => 'Тонкий (300)',
										400 => 'Нормальный (400)',
										500 => 'Средний (500)',
										600 => 'Полужирный (600)',
										700 => 'Жирный (700)',
										800 => 'Полутяжелый (800)',
										900 => 'Тяжелый (900)',
									),
									'default_value' => false,
									'return_format' => 'value',
									'multiple' => 0,
									'prepend' => '',
									'append' => '',
									'allow_null' => 0,
									'ui' => 0,
									'acfe_field_group_condition' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'allow_custom' => 0,
									'search_placeholder' => '',
									'min' => '',
									'max' => '',
								),
								array(
									'key' => 'field_64ccc44dd1016',
									'label' => 'Иконка',
									'name' => 'icon',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => 'Если нет иконки, оставьте поле пустым',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.33333333333',
										'class' => '',
										'id' => '',
									),
									'uploader' => '',
									'acfe_thumbnail' => 0,
									'return_format' => 'array',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'thumbnail',
									'acfe_field_group_condition' => 0,
									'library' => 'all',
								),
								array(
									'key' => 'field_64ccc489d1019',
									'label' => 'Ссылка',
									'name' => 'ssylka',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => 'Если элемент не является ссылкой, оставьте данное поле пустым',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.33333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'acfe_field_group_condition' => 0,
								),
								array(
									'key' => 'field_64ccc93ec9ce4',
									'label' => 'Уникальный класс',
									'name' => 'data_class',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => 'Только на латинском',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33.33333333333',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'acfe_field_group_condition' => 0,
								),
								array(
									'key' => 'field_65198fdf27687',
									'label' => 'Отступ справа в PX',
									'name' => 'margin-right',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'min' => '',
									'max' => '',
									'placeholder' => '',
									'step' => '',
									'prepend' => '',
									'append' => '',
									'acfe_field_group_condition' => 0,
								),
								array(
									'key' => 'field_6519904d49b42',
									'label' => 'Отступ слева в PX',
									'name' => 'margin-left',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'min' => '',
									'max' => '',
									'placeholder' => '',
									'step' => '',
									'prepend' => '',
									'append' => '',
									'acfe_field_group_condition' => 0,
								),
								array(
									'key' => 'field_6519914c8dc09',
									'label' => 'Отступ сверзу в PX',
									'name' => 'margin-top',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'min' => '',
									'max' => '',
									'placeholder' => '',
									'step' => '',
									'prepend' => '',
									'append' => '',
									'acfe_field_group_condition' => 0,
								),
								array(
									'key' => 'field_651991768dc0a',
									'label' => 'Отступ снизу в PX',
									'name' => 'margin-bottom',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'min' => '',
									'max' => '',
									'placeholder' => '',
									'step' => '',
									'prepend' => '',
									'append' => '',
									'acfe_field_group_condition' => 0,
								),
							),
							'acfe_group_modal_close' => 0,
							'acfe_group_modal_button' => '',
							'acfe_group_modal_size' => 'large',
							'parent_repeater' => 'field_64ccc421d1015',
						),
						array(
							'key' => 'field_651ae3b2eba0e',
							'label' => 'Кнопка',
							'name' => 'button',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_651ae1f8eba0c',
										'operator' => '==',
										'value' => 'modal_form_buttom',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_field_group_condition' => 0,
							'layout' => 'block',
							'acfe_seamless_style' => 0,
							'acfe_group_modal' => 0,
							'sub_fields' => array(
								array(
									'key' => 'field_651ae55ad12d5',
									'label' => 'Текст на кнопке',
									'name' => 'text',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '100',
										'class' => '',
										'id' => '',
									),
									'acfe_field_group_condition' => 0,
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_651af3c37b213',
									'label' => 'Отступ справа в PX',
									'name' => 'margin-right',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'acfe_field_group_condition' => 0,
									'default_value' => '',
									'min' => '',
									'max' => '',
									'placeholder' => '',
									'step' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_651af3f67b214',
									'label' => 'Отступ слева в PX',
									'name' => 'margin-left',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'acfe_field_group_condition' => 0,
									'default_value' => '',
									'min' => '',
									'max' => '',
									'placeholder' => '',
									'step' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_651af40e7b215',
									'label' => 'Отступ сверху в PX',
									'name' => 'margin-top',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'acfe_field_group_condition' => 0,
									'default_value' => '',
									'min' => '',
									'max' => '',
									'placeholder' => '',
									'step' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_651af4337b216',
									'label' => 'Отступ снизу в PX',
									'name' => 'margin-bottom',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'acfe_field_group_condition' => 0,
									'default_value' => '',
									'min' => '',
									'max' => '',
									'placeholder' => '',
									'step' => '',
									'prepend' => '',
									'append' => '',
								),
							),
							'acfe_group_modal_close' => 0,
							'acfe_group_modal_button' => '',
							'acfe_group_modal_size' => 'large',
							'parent_repeater' => 'field_64ccc421d1015',
						),
					),
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_64945486bfd14',
			'label' => 'Подвал сайта',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'no_preference' => 0,
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_649454abbfd15',
			'label' => 'Настройки подвала',
			'name' => 'footer_content',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_649454d4bfd16',
					'label' => 'Меню',
					'name' => 'menu',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Добавить',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_649454f6bfd17',
							'label' => 'Заголовок меню',
							'name' => 'menu_head',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_649454d4bfd16',
						),
						array(
							'key' => 'field_649455da85c29',
							'label' => 'Выберите меню',
							'name' => 'menuid',
							'aria-label' => '',
							'type' => 'menu',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'allow_null' => 0,
							'parent_repeater' => 'field_649454d4bfd16',
						),
					),
					'acfe_repeater_stylised_button' => 0,
				),
				array(
					'key' => 'field_6494560285c2a',
					'label' => 'Количество колонок меню в строке',
					'name' => 'menu_col',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => 6,
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64a6b4e7121bd',
					'label' => 'Дескриптор логотипа',
					'name' => 'logo_des',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'rows' => 2,
					'placeholder' => '',
					'new_lines' => 'br',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_649531b2a60ce',
					'label' => 'Дескриптор в подвале',
					'name' => 'deskriptor_v_podvale',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'rows' => 2,
					'placeholder' => '',
					'new_lines' => 'br',
					'acfe_textarea_code' => 0,
				),
				array(
					'key' => 'field_64952c51105ea',
					'label' => 'Цвет подвала',
					'name' => 'footer_color',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33333333333333333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 0,
					'return_format' => 'string',
					'display' => 'default',
					'button_label' => 'Select Color',
					'color_picker' => true,
					'absolute' => false,
					'input' => true,
					'allow_null' => true,
					'theme_colors' => false,
					'colors' => array(
					),
				),
				array(
					'key' => 'field_64952d3487932',
					'label' => 'Цвет текста',
					'name' => 'czvet_teksta',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.33333333333333333',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 0,
					'return_format' => 'string',
					'display' => 'default',
					'button_label' => 'Select Color',
					'color_picker' => true,
					'absolute' => false,
					'input' => true,
					'allow_null' => true,
					'theme_colors' => false,
					'colors' => array(
					),
				),
			
				array(
					'key' => 'field_6495270def1c7',
					'label' => 'Социальные сети',
					'name' => 'social',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Добавить',
					'acfe_field_group_condition' => 0,
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_64952728ef1c8',
							'label' => 'Название',
							'name' => 'name',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6495270def1c7',
						),
						array(
							'key' => 'field_64952732ef1c9',
							'label' => 'Ссылка',
							'name' => 'link',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6495270def1c7',
						),
						array(
							'key' => 'field_64952740ef1ca',
							'label' => 'Иконка',
							'name' => 'Icon',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
							'uploader' => '',
							'acfe_thumbnail' => 0,
							'parent_repeater' => 'field_6495270def1c7',
						),
						array(
							'key' => 'field_64a6a5bc85937',
							'label' => 'Цвет',
							'name' => 'color',
							'aria-label' => '',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_field_group_condition' => 0,
							'default_value' => '',
							'enable_opacity' => 0,
							'return_format' => 'string',
							'display' => 'default',
							'button_label' => 'Select Color',
							'color_picker' => 1,
							'absolute' => 0,
							'input' => 1,
							'allow_null' => 1,
							'theme_colors' => 0,
							'colors' => array(
							),
							'parent_repeater' => 'field_6495270def1c7',
						),
					),
				),
			),
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_6054c379b61ec',
			'label' => 'Контакты',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'no_preference' => 0,
		),
		array(
			'key' => 'field_5ea33f24a7c85',
			'label' => 'Основной телефон - шоркод: [acf field="phone" post_id="option"]',
			'name' => 'phone',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6059b33974016',
			'label' => 'Телефон 2 - шоркод: [acf field="phone2" post_id="option"]',
			'name' => 'phone2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_619bd7a073aaa',
			'label' => 'Все телефоны списком',
			'name' => 'phone_list',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Добавить',
			'acfe_field_group_condition' => 0,
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_650b613806773',
					'label' => 'Назначение',
					'name' => 'label',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'acfe_field_group_condition' => 0,
					'parent_repeater' => 'field_619bd7a073aaa',
				),
				array(
					'key' => 'field_650b612406772',
					'label' => 'Телефон',
					'name' => 'phone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'acfe_field_group_condition' => 0,
					'parent_repeater' => 'field_619bd7a073aaa',
				),
			),
		),
		array(
			'key' => 'field_62c8fb54f23d9',
			'label' => 'WhatsApp - шоркод: [acf field="whatsapp" post_id="option"]',
			'name' => 'whatsapp',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_635a9862f5715',
			'label' => 'Telegram - шоркод: [acf field="telegram" post_id="option"]',
			'name' => 'telegram',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_619cd3bd310a9',
			'label' => 'Вконтакте - шоркод: [acf field="vk" post_id="option"]',
			'name' => 'vk',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6481e3d6c9360',
			'label' => 'Viber - шоркод: [acf field="viber" post_id="option"]',
			'name' => 'viber',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_649527f06a125',
			'label' => 'Instagram - шоркод: [acf field="instagram" post_id="option"]',
			'name' => 'instagram',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5fca69540428f',
			'label' => 'Адрес - шоркод: [acf field="address" post_id="option"]',
			'name' => 'address',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_63ec4f0ec137a',
			'label' => 'Адрес в подвале сайта',
			'name' => 'adres_v_podvale_sajta',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ea33f6b6eb05',
			'label' => 'Почта',
			'name' => 'mail',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_63f28e08a676f',
			'label' => 'Режим работ',
			'name' => 'opening_hours',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'acfe_textarea_code' => 0,
		),
		array(
			'key' => 'field_64d106ded1558',
			'label' => 'Реквезиты',
			'name' => 'rekvezity',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => 'br',
			'acfe_field_group_condition' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'author',
		1 => 'comments',
		2 => 'tags',
		3 => 'discussion',
		4 => 'send-trackbacks',
		5 => 'excerpt',
		6 => 'permalink',
		7 => 'revisions',
		8 => 'categories',
		9 => 'the_content',
		10 => 'format',
		11 => 'slug',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_display_title' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
) );
} );

